name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "node-linter"
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with: 
          dockerfile: ./Dockerfile
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker container run "${IMAGE_NAME}" npm run lint
      -
        name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: mateocarciu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Push image to docker hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          tags: "mateocarciu/sayhello:${{ github.ref_name }}"
      -
        name: Push unstable image if branch is main
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          tags: "mateocarciu/sayhello:unstable"